- hosts: workstation
  #connection: local
  become: yes
  tasks:
##Create FrontEnd Instance
  - name: Create frontend instance
    include_role:
       name: osp-servers
       vars_from: frontend.yml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: osp-servers
       vars_from: app1.yml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: osp-servers
       vars_from: app2.yml
##Create DB server
  - name: Create db instance
    include_role:
       name: osp-servers
       vars_from: db.yml
# Old code, to call the main var file but I prefer the option before that calls each indepedent file
#  roles:
#    - osp-servers
#- hosts: workstation
#  become: yes
#  roles:
#    - osp-servers
