---
# vars file for osp.servers
# Actually this file is not used, instead each instance have its own file...... will improve this later
osp_servers:
  frontend: # To crate the frontend instance
    instance_name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
  app1: # To crate the app1 instance
    instance_name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    instance_name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  db:
    instance_name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}
